
server:
  port: 9033

spring:
  jpa:
    generate-ddl: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: doctor
    nonSecurePort: 80
ribbon: 
   eureka: 
     enabled: true
