
server:
  port: 9023


eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
      registerWithEureka: true
      fetchRegistry: true
  instance:
    hostname: gateway
    nonSecurePort: 80

---
spring:
  profiles: cloud
