discovery:
  image: spring-cloud/microservices-hospitalsystem-eureka-service
  ports:
   - "8761:8761"
gateway:
  image: spring-cloud/microservices-hospitalsystem-gateway
  ports:
   - "9023:9023"
  links:
   - discovery
   - doctor
   - patient
doctor:
  image: spring-cloud/microservices-hospitalsystem-doctor-service
  ports:
     - "9033:9033"
  links:
   - discovery
patient:
  image: spring-cloud/microservices-hospitalsystem-patient-service
  ports:
     - "9903:9903"
  links:
   - discovery